// filter categories
const categories = [
  {
    name: 'All',
    filter: 'all',
  },
  {
    name: 'Landscape',
    filter: 'landscape',
  },
  {
    name: 'Portrait',
    filter: 'portrait',
  },
  {
    name: 'Wedding',
    filter: 'wedding',
  },
  {
    name: 'Drone',
    filter: 'drone',
  },
  {
    name: 'Birds',
    filter: 'birds',
  },
  {
    name: 'Animal',
    filter:'animal',
  },
  {
    name: 'Forest',
    filter: 'forest',
  },
  {
    name: 'Galaxy',
    filter: 'galaxy',
  },
  {
    name: 'Mountain',
    filter:'mountain',
  },
];

const images = [
  {
    id: '1',
    url: 'wave.jpg',
    category: 'landscape',
    title: 'Wave',
  },
  {
    id: '2',
    url: 'aurora.jpg',
    category: 'landscape',
    title: 'Aurora',
  },
  {
    id: '3',
    url: 'wedding2.jpg',
    category: 'wedding',
    title: 'Wedding 2',
  },
  {
    id: '4',
    url: 'seadrone.jpg',
    category: 'drone',
    title: 'Beach and Sea from drone',
  },
  {
    id: '5',
    url: 'mountain.jpg',
    category: 'landscape',
    title: 'Mountain',
  },
  {
    id: '6',
    url: 'roaddrone.jpg',
    category: 'drone',
    title: 'Road from Drone',
  },
  {
    id: '7',
    url: 'portrait1.jpg',
    category: 'portrait',
    title: 'Portrait 1',
  },
  {
    id: '8',
    url: 'wedding1.jpg',
    category: 'wedding',
    title: 'Wedding 1',
  },
  {
    id: '9',
    url: 'hills.jpg',
    category: 'landscape',
    title: 'Hills',
  },
  {
    id: '11',
    url: 'portrait2.jpg',
    category: 'portrait',
    title: 'Portrait 2',
  },
  {
    id: '12',
    url: 'lake.jpg',
    category: 'landscape',
    title: 'Lake',
  },
  {
    id: '13',
    url: 'landscape01.jpg',
    category: 'landscape',
    title: 'Landscape lake',
  },
  {
    id: '14',
    url: 'landscapeSnow.jpg',
    category: 'landscape',
    title: 'Mountain Snowy',
  },
  {
    id: '15',
    url: 'aurora2.jpg',
    category: 'landscape',
    title: 'Aurora2',
  },
  {
    id: '16',
    url: 'greenMountain.jpg',
    category: 'landscape',
    title: 'Mountain Green',
  },
  {
    id: '17',
    url: 'portrait3.jpg',
    category: 'portrait',
    title: 'Portrait 3',
  },
  {
    id: '18',
    url: 'portrait4.jpg',
    category: 'portrait',
    title: 'Portrait 4',
  },
  {
    id: '19',
    url: 'portrait5.jpg',
    category: 'portrait',
    title: 'Portrait 5',
  },
  {
    id: '20',
    url: 'portrait6.jpg',
    category: 'portrait',
    title: 'Portrait 6',
  },
  {
    id: '21',
    url: 'portrait7.jpg',
    category: 'portrait',
    title: 'Portrait 7',
  },
  {
    id: '22',
    url: 'wedding3.jpg',
    category: 'wedding',
    title: 'Wedding ',
  },
  {
    id: '23',
    url: 'wedding4.jpg',
    category: 'wedding',
    title: 'Wedding ',
  },
  {
    id: '24',
    url: 'wedding5.jpg',
    category: 'wedding',
    title: 'Wedding ',
  },
  {
    id: '25',
    url: 'wedding6.jpg',
    category: 'wedding',
    title: 'Wedding ',
  },
  {
    id: '26',
    url: 'drone1.jpg',
    category: 'drone',
    title: 'Drone 1',
  },
  {
    id: '27',
    url: 'drone2.jpg',
    category: 'drone',
    title: 'Drone 2',
  },
  {
    id: '28',
    url: 'drone3.jpg',
    category: 'drone',
    title: 'Drone 3',
  },
  {
    id: '29',
    url: 'drone4.jpg',
    category: 'drone',
    title: 'Drone 4',
  },
  {
    id: '30',
    url: 'drone5.jpg',
    category: 'drone',
    title: 'Drone 5',
  },
  {
    id: '31',
    url: 'bird1.jpg',
    category: 'birds',
    title: 'Birds 1',
  },
  {
    id: '32',
    url: 'bird2.jpg',
    category: 'birds',
    title: 'Birds 2',
  },
  {
    id: '33',
    url: 'bird3.jpg',
    category: 'birds',
    title: 'Birds 3',
  },
  {
    id: '34',
    url: 'bird4.jpg',
    category: 'birds',
    title: 'Birds 4',
  },
  {
    id: '35',
    url: 'bird5.jpg',
    category: 'birds',
    title: 'Birds 5',
  },

  {
    id: '36',
    url: 'bird6.jpg',
    category: 'birds',
    title: 'Birds 6',
  },
  {
    id: '37',
    url: 'bird7.jpg',
    category: 'birds',
    title: 'Birds 7',
  },
  {
    id: '38',
    url: 'bird8.jpg',
    category: 'birds',
    title: 'Birds 8',
  },
  {
    id: '39',
    url: 'bird9.jpg',
    category: 'birds',
    title: 'Birds 9',
  },
  {
    id: '40',
    url: 'bird10.jpg',
    category: 'birds',
    title: 'Birds 10',
  },
  {
    id: '41',
    url: 'bird11.jpg',
    category: 'birds',
    title: 'Birds 11',
  },
  {
    id: '42',
    url: 'bird12.jpg',
    category: 'birds',
    title: 'Birds 12',
  },
  {
    id: '43',
    url: 'bird13.jpg',
    category: 'birds',
    title: 'Birds 13',
  },
  {
    id: '44',
    url: 'bird14.jpg',
    category: 'birds',
    title: 'Birds 14',
  },
  {
    id: '45',
    url: 'bird15.jpg',
    category: 'birds',
    title: 'Birds 15',
  },

  {
    id: '46',
    url: 'bird16.jpg',
    category: 'birds',
    title: 'Birds 16',
  },
  {
    id: '47',
    url: 'bird17.jpg',
    category: 'birds',
    title: 'Birds 17',
  },
  {
    id: '48',
    url: 'bird18.jpg',
    category: 'birds',
    title: 'Birds 18',
  },
  {
    id: '49',
    url: 'bird19.jpg',
    category: 'birds',
    title: 'Birds 19',
  },
  {
    id: '50',
    url: 'bird20.jpg',
    category: 'birds',
    title: 'Birds 20',
  },
  {
    id: '51',
    url: 'animal1.jpg',
    category: 'animal',
    title: 'animal 1',
  },
  {
    id: '52',
    url: 'animal2.jpg',
    category: 'animal',
    title: 'animal 2',
  },
  {
    id: '53',
    url: 'animal3.jpg',
    category: 'animal',
    title: 'animal 3',
  },
  {
    id: '54',
    url: 'animal4.jpg',
    category: 'animal',
    title: 'animal 4',
  },
  {
    id: '55',
    url: 'animal5.jpg',
    category: 'animal',
    title: 'animal 5',
  },
  {
    id: '56',
    url: 'animal6.jpg',
    category: 'animal',
    title: 'animal 6',
  },
  {
    id: '57',
    url: 'animal7.jpg',
    category: 'animal',
    title: 'animal 7',
  },
  {
    id: '58',
    url: 'animal8.jpg',
    category: 'animal',
    title: 'animal 8',
  },
  {
    id: '59',
    url: 'animal9.jpg',
    category: 'animal',
    title: 'animal 9',
  },
  {
    id: '60',
    url: 'animal10.jpg',
    category: 'animal',
    title: 'animal 10',
  },
  {
    id: '61',
    url: 'animal11.jpg',
    category: 'animal',
    title: 'animal 11',
  },
  {
    id: '62',
    url: 'animal12.jpg',
    category: 'animal',
    title: 'animal 12',
  },
  {
    id: '63',
    url: 'f1.jpg',
    category: 'forest',
    title: 'f 1',
  },
  {
    id: '64',
    url: 'f2.jpg',
    category: 'forest',
    title: 'f 2',
  },
  {
    id: '65',
    url: 'f3.jpg',
    category: 'forest',
    title: 'f 3',
  },
  {
    id: '66',
    url: 'f4.jpg',
    category: 'forest',
    title: 'f 4',
  },
  {
    id: '67',
    url: 'f5.jpg',
    category: 'forest',
    title: 'f 5',
  },
  {
    id: '68',
    url: 'f6.jpg',
    category: 'forest',
    title: 'f 6',
  },
  {
    id: '69',
    url: 'f7.jpg',
    category: 'forest',
    title: 'f 7',
  },
  {
    id: '70',
    url: 'f8.jpg',
    category: 'forest',
    title: 'f 8',
  },
  {
    id: '71',
    url: 'f9.jpg',
    category: 'forest',
    title: 'f 9',
  },
  {
    id: '72',
    url: 'f10.jpg',
    category: 'forest',
    title: 'f 10',
  },
  {
    id: '73',
    url: 'f11.jpg',
    category: 'forest',
    title: 'f 11',
  },
  {
    id: '74',
    url: 'f12.jpg',
    category: 'forest',
    title: 'f 12',
  },
  {
    id: '75',
    url: 'f13.jpg',
    category: 'forest',
    title: 'f 13',
  },
  {
    id: '76',
    url: 'f14.jpg',
    category: 'forest',
    title: 'f 14',
  },
  {
    id: '77',
    url: 'f15.jpg',
    category: 'forest',
    title: 'f 15',
  },
  {
    id: '78',
    url: 'g1.jpg',
    category: 'galaxy',
    title:'g 1',
  },
  {
    id: '79',
    url: 'g2.jpg',
    category: 'galaxy',
    title:'g 2',
  },
  {
    id: '80',
    url: 'g3.jpg',
    category: 'galaxy',
    title:'g 3',
  },
  {
    id: '81',
    url: 'g4.jpg',
    category: 'galaxy',
    title:'g 4',
  },
  {
    id: '82',
    url: 'g5.jpg',
    category: 'galaxy',
    title:'g 5',
  },
  {
    id: '83',
    url: 'g6.jpg',
    category: 'galaxy',
    title:'g 6',
  },
  {
    id: '84',
    url: 'g7.jpg',
    category: 'galaxy',
    title:'g 7',
  },
  {
    id: '85',
    url: 'g8.jpg',
    category: 'galaxy',
    title:'g 8',
  },
  {
    id: '86',
    url: 'g9.jpg',
    category: 'galaxy',
    title:'g 9',
  },
  {
    id: '87',
    url: 'g10.jpg',
    category: 'galaxy',
    title:'g 10',
  },
  {
    id: '88',
    url: 'm1.jpg',
    category: 'mountain',
    title:'m 1',
  },
  {
    id: '89',
    url: 'm2.jpg',
    category: 'mountain',
    title:'m 2',
  },
  {
    id: '90',
    url: 'm3.jpg',
    category: 'mountain',
    title: 'm 3',
  },

  {
    id: '91',
    url: 'm4.jpg',
    category: 'mountain',
    title:'m 4',
  },
  {
    id: '92',
    url: 'm5.jpg',
    category: 'mountain',
    title:'m 5',
  },
  {
    id: '93',
    url: 'm6.jpg',
    category: 'mountain',
    title: 'm 6',
  },
  {
    id: '94',
    url: 'm7.jpg',
    category: 'mountain',
    title:'m 7',
  },
  {
    id: '95',
    url: 'm8.jpg',
    category: 'mountain',
    title:'m 8',
  },
  {
    id: '96',
    url: 'm9.jpg',
    category: 'mountain',
    title: 'm 9',
  },
  
  {
    id: '97',
    url: 'm10.jpg',
    category: 'mountain',
    title:'m 10',
  },
  {
    id: '98',
    url: 'm11.jpg',
    category: 'mountain',
    title:'m 11',
  },
  {
    id: '99',
    url: 'm12.jpg',
    category: 'mountain',
    title: 'm 12',
  },
  
];